# Generated by Django 5.0.6 on 2024-07-26 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objectif', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectiffinancier',
            old_name='objectif',
            new_name='cout',
        ),
    ]
